### PR TITLE
IDI-146: Minify the Infusion JS and fix some tests

### PR DESCRIPTION
**Pull request by acheetham**

### CODE REVIEW

**Comment by jobara** [comment]
@acheetham I don't think we want to use the minified version of infusion in the repo. It will be hard for development, in particular with debugging. This will also be the case for those who want the source version of the VideoPlayer.

It appears that the a minified version of infusion is already included in the videoPlayer-all-min.js file. If this isn't enough we could consider one of these options:
1. include a source and min version of all lib packages
2. use the grunt build script to minify all of the lib files and not just the single concatenated one

**Comment by acheetham** [comment]
@jobara, the reason I included a minified MyInfusion is because the UIO fat panel frame needs its own copy of Infusion – but it doesn't need the full video player in there. One option would be to use the videoPlayer-all-min.js inside the frame...

**Comment by jobara** [comment]
@acheetham hmm.. maybe we could do that.. if the browser is cacheing the file it would probably be faster than loading a separate file, but we could also consider the two options i suggested.

**Comment by acheetham** [comment]
@jobara, I'm not sure I understand how the second option you suggested would actually be used/helpful. Which option do you think is best?

**Comment by jobara** [comment]
@acheetham option 2 would be about minifying the MyInfusion.js file that is included in the lib directory with the videoPlayers own build script. This way we would have the source version when developing but someone who picks the minified build of the video player would have a minified version of infusion in there too.

**Comment by acheetham** [comment]
ah - ok, that option 2 sounds like the way to go

**Comment by jobara** [comment]
@acheetham i think we'll need to update the current build script though. I believe they only minify the concatenated file.

**Comment by acheetham** [comment]
@jobara, as we discussed, I've added a minified MyInfusion alongside the unminified one, as an interim solution before we update the VP to the latest Infusion. We need to completely reconsider how we handle this issue, of infusion-for-the-vp and infusion-for-uio, but as we discussed, this temporary change should hold us for now.

**Comment by colinbdclark** [comment]
@acheetham Is there a JIRA that covers the work to reconsider how we manage Infusion builds for the Video Player and UIO--just so we don't forget about it later?

**Comment by acheetham** [comment]
@colinbdclark, not yet, but I will be creating one

**Comment by jobara** [comment]
@acheetham could you add a link to that jira in the comments here.

**Comment by acheetham** [comment]
Here's the JIRA: https://issues.fluidproject.org/browse/VP-333
It is also linked to https://issues.fluidproject.org/browse/FLUID-4394, which is related.

**Comment by jobara** [comment]
The "Video Player Controls Integration Test Suite" doesn't complete. This appears to also be an issue in master. I've filed [VP-334](https://issues.fluidproject.org/browse/VP-334).

**Comment by jobara** [comment]
@acheetham the "Video Player Test Suite" is not completing. This may be related to the amara api changes. The following errors are being thrown in the console.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (path.html, line 0)
[Error] Failed to load resource: Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers. (subtitles, line 0)
[Error] XMLHttpRequest cannot load https://www.amara.org/api/videos/g2QoNQgjJd5y/languages/en/subtitles/. Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers. (VideoPlayer-test.html, line 0)

**Comment by jobara** [comment]
@acheetham the "Video Player Integration Test Suite" is also failing.

**Comment by jobara** [comment]
@acheetham the "Video Player Transcript Test Suite" is also failing. Probably because of the amara api changes.

**Comment by acheetham** [comment]
Regarding the VIdeo Player Test Suite failing: The entire suite actually passes in FF, fails as described in Safari, and succeeds (for the most part) in Chrome.

**Comment by acheetham** [comment]
Regarding the failing Video Player Integration Test Suite: This fails in exactly the same way in the current master.

**Comment by acheetham** [comment]
Regarding the failing Video Player Transcript Test Suite: This suite completes successfully in FF (1 in 10 runs might have some timing issues); fails as described in Safari; succeeds but has timing issues in Chrome.

**Comment by jobara** [comment]
@acheetham I've tried this out again and your changes do seem to be an improvement over the current, in master, implementation. I'll merge this in, but could you please make sure that there are JIRAS filed for the known issues.

**Comment by jobara** [comment]
merged at a20c6a3d632af2bd2e38090aa5a19dfc868a0c15

**Pull request merged**
